name: "cd"
run-name: ${{ github.ref_name }}
on:
  push:
    tags:
      - '*'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: artifact
      - run: cat artifact/foo.txt