name: "cd"
run-name: ${{ github.ref_name }}
on:
  push:
    tags:
      - '*'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building ${{ github.ref_name }}"