name: "cd"
run-name: "create release and tag repo"
on:
  push:
    tags:
      - '*'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: cat foo.txt