name: dev-ci
on:
  push:
    branches:
      - feature/**
      - hotfix/**

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Generate Tag
        run: echo {{ github.ref }}-${{github.run_number}}
        
